config/routes.rb
Rails.application.routes.draw do
  resource :accounts, only: [:show, :new, :create, :edit]
  resource :cart, only: [:show]
  resource :programs
  resource :store do
    post :checkout
  end
  resource :students, only: [:show, :new, :create, :edit]
  resources :order_items, only: [:create, :update, :destroy]


  post "/hook" => "stores#hook"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  root 'welcome#index'
  # resource :welcome, only: [ :index ]
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  belongs_to :order_status
  has_many :order_items

  before_create :set_order_status
  before_save :update_subtotal
  before_update :update_total

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  serialize :notification_params, Hash

  def paypal_url(return_path)
    values = {
        business: "seller@bl.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: '1.11',
        item_name: 'some product',
        item_number: '1',
        quantity: '1',
        notify_url: "#{Rails.application.secrets.app_host}/hook"
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

  private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

  def update_total
    total =
        self.update()
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :program
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :program_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      program.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def program_present
    if program.nil?
      errors.add(:program, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_one :account

  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
    :omniauth_providers => [:facebook]

  has_many :students

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

      name = auth.info.name.split(" ")
      user.first_name = name[0]   # assuming the user model has a name
      user.last_name = name[1]   # assuming the user model has a name

      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def cart
    @cart ||= []
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def show
    @student = Student.new
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    if @account.save
      redirect_to accounts_path, notice: "Account Created!"
    else
      redirect_to :back, notice: "Sorry. There was an error. "
    end
  end

  def edit
  end

  private

  def account_params
    params.require(:account).permit(:email)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    @program = Program.all
    @order_item = current_order.order_items.new
  end


  def show
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end

  def login
  end

  def register
  end

  def checkout
  end

  def account
  end

  def print_materials
  end

  def program_exercises
  end

  def admin
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  protect_from_forgery except: [:hook]

  def index
    @programs = Program.all
    @order_item = current_order.order_items.new
  end

  def show
    @programs = Program.all
    @order_item = current_order.order_items.new
  end


  def checkout
    @new_order = current_order
    redirect_to @new_order.paypal_url(accounts_path)
  end

  def hook
    binding.pry
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @order = Order.find params[:invoice]
      @order.order_status.update_attributes notification_params: params, status: status, transaction_id: params[:txn_id], purchased_at: Time.now
    end
    render nothing: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
               concat message
      end)
    end
    nil
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link cart-text" %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_headers.html.erb
<meta name="keywords" content="education,therapy,brain" />
<meta name="description" content="Launch Pad for Your Child's Success" />
<meta name="Author" content="Dr. Don Helms" />
<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />
<link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="assets/plugins/slider.revolution/css/extralayers.css" rel="stylesheet" type="text/css" />
<link href="assets/plugins/slider.revolution/css/settings.css" rel="stylesheet" type="text/css" />
<link href="assets/css/essentials.css" rel="stylesheet" type="text/css" />
<link href="assets/css/layout.css" rel="stylesheet" type="text/css" />
<link href="assets/css/header-1.css" rel="stylesheet" type="text/css" />
<link href="assets/css/color_scheme/green.css" rel="stylesheet" type="text/css" id="color_scheme" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrainLaunch</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />
  </head>
  <body class="boxed">
    <%= render partial: 'nav/top_nav'  %>
  </nav>
  <div class="container">
    <div>
      <%= render partial: 'layouts/flash_messages'  %>
    </div>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/nav/_top_fixed.html.erb
<div id="navbar" class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <li><%= link_to("Store", store_path) %></li>
    <li><a>Programs</a></li>
    <li><%= link_to("Printable Materials", programs_path) %></li>
    <li><a>Program Exercises</a></li>
    <li><%= render 'layouts/cart_text' %></li>
  </ul>
</div>

app/views/nav/_top_nav.html.erb
<!-- wrapper -->
<div id="wrapper">
  <div id="header" class="sticky shadow-after-3 clearfix">
    <div class="container">
      <header id="topNav">
        <a class="logo pull-left" href="https://www.brainlaunch.com/index2.php" target="_self">
          <%= image_tag("blogo126x80.png") %>
        </a>
        <div class="navbar-collapse pull-right nav-main-collapse collapse">
          <nav class="nav-main">
            <ul id="topMain" class="nav nav-pills nav-main">
              <li class="dropdown">
                <a class="dropdown-toggle" href="https://www.brainlaunch.com/index2.php">
                  HOME
                  </a>
              </li>
              <li class=""><!-- ABOUT US -->
                <a class="" href="https://www.brainlaunch.com/index2.php/about-us/">
                  ABOUT US
                  </a>
              </li>
              <li class="dropdown"><!-- PROGRAM -->
                <a class="dropdown-toggle" href="https://www.brainlaunch.com/index2.php/program/">
                  PROGRAM
                  </a>
              </li>
              <li class="dropdown mega-menu"><!-- STORE -->
                <%= link_to("STORE", store_path) %>
              </li>
              <li class="dropdown"><!-- BLOG -->
                <a class="dropdown-toggle" href="https://www.brainlaunch.com/index2.php/blog/">
                  BLOG
                    </a>
              </li>
              <li class="dropdown"><!-- VIDEOS -->
                <a class="dropdown-toggle" href="https://www.brainlaunch.com/index2.php/videos/">
                  VIDEOS
                    </a>
              </li>
              <% if user_signed_in? %>
                <li class="dropdown mega-menu">
                  <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">WELCOME, <%= current_user.first_name.upcase %><span class="caret"></span></a>
                  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel">
                    <li><%= link_to('Account', accounts_path ) %></li>
                    <li><%= render 'layouts/cart_text' %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                  </ul>
                </li>
              <% else %>
                <li class="dropdown">
                  <a class="" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">LOGIN<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li role="separator" class="divider"></li>
                    <%= link_to user_omniauth_authorize_path(:facebook) do %>
                      <li><i class="fa fa-facebook"></i> Facebook</li>
                      <!-- PATH TO USER FOR EXTERNAL AUTH -->
                      <!-- {{ROOT}}/users/auth/facebook -->
                    <% end %>
                  </ul>
                <% end %>
              </ul>
            </li>
          </nav></div>
      </header>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
		<!-- FOOTER -->
			<footer id="footer">
			  <div class="copyright">
				  <div class="container">
						<ul class="pull-right nomargin list-inline mobile-block">
							<li><a href="#">Terms &amp; Conditions</a></li>
							<li>&bull;</li>
							<li><a href="#">Privacy</a></li>
						</ul>
						&copy; All Rights Reserved, Brain Launch
					</div>
				</div>
			</footer>
			<!-- /FOOTER -->

					</div>
					<!-- /wrapper -->


					<!-- SCROLL TO TOP -->
					<a href="#" id="toTop"></a>


					<!-- PRELOADER -->
					<div id="preloader">
						<div class="inner"></div>
					</div><!-- /PRELOADER -->


					<!-- JAVASCRIPT FILES -->
					<script type="text/javascript">var plugin_path = 'assets/plugins/';</script>
					<script type="text/javascript" src="assets/plugins/jquery/jquery-2.1.4.min.js"></script>

					<script type="text/javascript" src="assets/js/scripts.js"></script>

					<!-- STYLESWITCHER - REMOVE
					<script async type="text/javascript" src="assets/plugins/styleswitcher/styleswitcher.js"></script> -->
					<!-- REVOLUTION SLIDER -->
					<script type="text/javascript" src="assets/plugins/slider.revolution/js/jquery.themepunch.tools.min.js"></script>
					<script type="text/javascript" src="assets/plugins/slider.revolution/js/jquery.themepunch.revolution.min.js"></script>
					<script type="text/javascript" src="assets/js/view/demo.revolution_slider.js"></script>
				</body>
			</html>

app/views/welcome/_callout1.html.erb
<!-- /REVOLUTION SLIDER -->
<!-- CALLOUT -->
<div class="alert alert-transparent bordered-bottom nomargin">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-12"><!-- left text -->
        <h3>Request the<span><strong> FREE Pre-Launch Program</strong></span> for 4 and 5 year olds!</h3>
        <p class="font-lato weight-300 size-20 nomargin-bottom">
          Launch Pad for YOUR Child's Success!<!-- /left text -->
        </p>
      </div>
      <div class="col-md-3 col-sm-12 text-left"><!-- right btn -->
        <a href="https://www.brainlaunch.com/index2.php/contact/" rel="nofollow" target="_self" class="btn btn-primary btn-lg">GET PRE-LAUNCH <NOW></NOW></a>
      </div>
      <!-- /right btn -->
    </div>
  </div>
</div>

app/views/welcome/_callout2.html.erb
<!-- -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-sm-5">
        <a class="image-hover lightbox thumbnail" href="http://vimeo.com/166930720" data-plugin-options='{"type":"iframe"}'>
          <span class="image-hover-icon image-hover-light"><!-- image-hover-light | image-hover-dark -->
            <i class="fa fa-vimeo-square"><!-- video icon --></i>
          </span>
          <img class="img-responsive" src="assets/images/foundation960x832.png" alt="Learn About the Foundational Brain Systems">
        </a>
      </div>
      <div class="col-md-7 col-sm-7">
        <header class="margin-bottom-60">
          <h3>Brain Launch <br>
            Launch Pad for a Child's Success</h3>
        </header>
        <blockquote>
          <h1 class="lead font-lato">Here is a video overview of the 'Foundational Brain Systems&quot; Model.
                    Parents can overcome the problems caused by too much video time and not enough 3D real world activity. Hand eye coordination is just the &quot;tip of the iceberg&quot; of the problems caused by underdeveloped Foundational Brain Systems. Reviewing the larger framework of the brain, 'Informational Processing System&quot; can be strengthend with basic exercises designed to focus on the FBS.</h1>
        </blockquote>
        <a class="btn btn-default btn-lg size-15 margin-top-30 lightbox" href="http://vimeo.com/166930720" data-plugin-options='{"type":"iframe"}'>WATCH VIDEO</a>
      </div>
    </div>
  </div>
</section>
<!-- / -->

app/views/welcome/_goodies.html.erb
<!-- Goodies -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="box-icon box-icon-center box-icon-transparent box-icon-large">
          <a class="box-icon-title" href="#">
            <i class="fa fa-tablet"></i>
            <h2>Social Mission</h2>
          </a>
          <p class="text-muted">Affordable, easy-to-administer programs to advance a child's brain development in today's society</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box-icon box-icon-center box-icon-transparent box-icon-large">
          <a class="box-icon-title" href="#">
            <i class="fa fa-random"></i>
            <h2>Information Processing System of the Brain</h2>
          </a>
          <p class="text-muted">The Foundational Brain Systems</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box-icon box-icon-center box-icon-transparent box-icon-large">
          <a class="box-icon-title" href="#">
            <i class="fa fa-tint"></i>
            <h2>Ultimate Software of the Brain</h2>
          </a>
          <p class="text-muted">Construct of Synergistic Intellect</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box-icon box-icon-center box-icon-transparent box-icon-large">
          <a class="box-icon-title" href="#">
            <i class="fa fa-cogs"></i>
            <h2>Power Supply for the Brain</h2>
          </a>
          <p class="text-muted">Nutrition and Exercises</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Goodies -->

app/views/welcome/_parallax_section.html.erb
<!-- PARALLAX -->
<section class="parallax parallax-2 padding-xxs" style="background-image: url('assets/images/demo/vision-min.jpg');">
  <div class="overlay dark-4"><!-- dark overlay [0 to 9 opacity] --></div>
  <div class="container">
    <div class="row countTo-md text-center">
      <div class="col-xs-6 col-sm-3">
        <i class="fa fa-users"></i>
        <h5>A child's brain development in today's society</h5>
      </div>
      <div class="col-xs-6 col-sm-3">
        <i class="fa fa-code"></i>
        <h5>Information Processing System of the Brain</h5>
      </div>
      <div class="col-xs-6 col-sm-3">
        <i class="fa fa-twitter"></i>
        <h5>TWITTER</h5>
      </div>
      <div class="col-xs-6 col-sm-3">
        <i class="fa fa-facebook"></i>
        <h5>FACEBOOK</h5>
      </div>
    </div>
  </div>
</section>
<!-- /PARALLAX -->

app/views/welcome/_slider.html.erb
<section id="slider" class="fullwidthbanner-container roundedcorners">
  <div class="fullscreenbanner" data-navigationStyle="preview4">
    <ul class="hide">
      <!-- SLIDE -->
      <li data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off" data-title="" data-thumb="assets/images/demo/video/neuron_thumb.jpg">
        <%= image_tag("1x1.png", data: { lazyload: "neuron.jpg", bgposition: 'center center', bgfit: 'cover', bgrepeat: 'no-repeat'}, alt: 'video') %>
        <div class="tp-caption tp-fade fadeout fullscreenvideo"
                data-x="0"
                data-y="0"
                data-speed="1000"
                data-start="1100"
                data-easing="Power4.easeOut"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1500"
                data-endeasing="Power4.easeIn"
                data-autoplay="true"
                data-autoplayonlyfirsttime="false"
                data-nextslideatend="true"
                data-volume="mute"
                data-forceCover="1"
                data-aspectratio="16:9"
                data-forcerewind="on" style="z-index: 2;">
          <div class="overlay dark-4"></div>
          <video class="fullvideo" preload="none" poster="assets/images/demo/video/neuron.jpg">
            <source src="assets/images/demo/video/neuron.webm" type="video/webm" />
            <source src="assets/images/demo/video/neuron.mp4" type="video/mp4" />
          </video>
        </div>
        <div class="tp-caption customin ltl tp-resizeme text_white"
                data-x="center"
                data-y="180"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1000"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 3;">
          <span class="weight-300">Launch Pad for a Child's Success</span>
        </div>
        <div class="tp-caption customin ltl tp-resizeme large_bold_white"
                data-x="center"
                data-y="230"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1200"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 3;">
          WELCOME TO BRAIN LAUNCH
              </div>
        <div class="tp-caption customin ltl tp-resizeme small_light_white"
                data-x="center"
                data-y="350"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1400"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 3; width: 750px; max-width: 750px; white-space: normal; text-align:center;">
          Providing affordable, easy-to-administer programs that will start children on a journey towards actualizing their true potential.
              </div>
        <div class="tp-caption customin ltl tp-resizeme"
                data-x="center"
                data-y="438"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1550"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 3;">
          <a href="#purchase" class="btn btn-default btn-lg">
            <span>Purchase Brain Launch Program One Now!</span>
          </a>
          <a href="#purchase" class="btn btn-default btn-lg">
            <span>Purchase Brain Launch Program Two Now!</span>
          </a>
        </div>
      </li>
      <!-- SLIDE  -->
      <li data-transition="random" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off" > <!-- data-title="Slide title 1" data-thumb="assets/images/demo/150x99/27-min.jpg">  -->
        <img src="assets/images/1x1.png" data-lazyload="assets/images/demo/1200x800/31-min.jpg" alt="" data-bgfit="cover" data-bgposition="center bottom" data-bgrepeat="no-repeat" />
        <div class="overlay dark-4"><!-- dark overlay [1 to 9 opacity] --></div>
        <div class="tp-caption customin ltl tp-resizeme text_white"
                data-x="center"
                data-y="180"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1000"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 10;">
          <span class="weight-300">Launch Pad for a Child's Success</span>
        </div>
        <div class="tp-caption customin ltl tp-resizeme large_bold_white"
                data-x="center"
                data-y="230"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1200"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 10;">
          WELCOME TO BRAIN LAUNCH
              </div>
        <div class="tp-caption customin ltl tp-resizeme small_light_white"
                data-x="center"
                data-y="350"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1400"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 10; width: 750px; max-width: 750px; white-space: normal; text-align:center;">
          Providing affordable, easy-to-administer programs that will start children on a journey towards actualizing their true potential.
              </div>
        <div class="tp-caption customin ltl tp-resizeme"
                data-x="center"
                data-y="438"
                data-customin="x:0;y:150;z:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-speed="800"
                data-start="1550"
                data-easing="easeOutQuad"
                data-splitin="none"
                data-splitout="none"
                data-elementdelay="0.01"
                data-endelementdelay="0.1"
                data-endspeed="1000"
                data-endeasing="Power4.easeIn" style="z-index: 10;">
          <a href="#purchase" class="btn btn-default btn-lg">
            <span>Purchase Brain Launch Program One Now!</span>
          </a>
          <a href="#purchase" class="btn btn-default btn-lg">
            <span>Purchase Brain Launch Program Two Now!</span>
          </a>
        </div>
      </li>
    </ul>
  </div>
</section>

app/views/welcome/index.html.erb
<%= render partial: 'slider' %>
<%= render partial: 'callout1' %>
<%= render partial: 'callout2' %>
<%= render partial: 'parallax_section' %>
<%= render partial: 'goodies' %>