config/routes.rb
Rails.application.routes.draw do
  resource :accounts, only: [:show, :new, :create, :edit]
  resource :cart, only: [:show]
  resource :programs
  resource :store do
    post :checkout
  end
  resource :students, only: [:show, :new, :create, :edit]
  resources :order_items, only: [:create, :update, :destroy]


  post "/hook" => "stores#hook"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  root 'welcome#index'
  # resource :welcome, only: [ :index ]
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  belongs_to :order_status
  has_many :order_items

  before_create :set_order_status
  before_save :update_subtotal
  before_update :update_total

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  serialize :notification_params, Hash

  def paypal_url(return_path)
    values = {
        business: "seller@bl.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: '1.11',
        item_name: 'some product',
        item_number: '1',
        quantity: '1',
        notify_url: "#{Rails.application.secrets.app_host}/hook"
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

  private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

  def update_total
    total =
        self.update()
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :program
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :program_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      program.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def program_present
    if program.nil?
      errors.add(:program, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_one :account

  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
    :omniauth_providers => [:facebook]

  has_many :students

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

      name = auth.info.name.split(" ")
      user.first_name = name[0]   # assuming the user model has a name
      user.last_name = name[1]   # assuming the user model has a name

      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def cart
    @cart ||= []
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def show
    @student = Student.new
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    if @account.save
      redirect_to accounts_path, notice: "Account Created!"
    else
      redirect_to :back, notice: "Sorry. There was an error. "
    end
  end

  def edit
  end

  private

  def account_params
    params.require(:account).permit(:email)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_order

  def current_order
    begin
      unless session[:order_id].nil?
        Order.find(session[:order_id])
      else
        Order.new(user_id: current_user.id)
      end
    rescue
      Order.new(user_id: current_user.id)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    @program = Program.all
    @order_item = current_order.order_items.new
  end


  def show
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end

  def login
  end

  def register
  end

  def checkout
  end

  def account
  end

  def print_materials
  end

  def program_exercises
  end

  def admin
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  protect_from_forgery except: [:hook]

  def index
    @programs = Program.all
    @order_item = current_order.order_items.new
  end

  def show
    @programs = Program.all
    @order_item = current_order.order_items.new
  end


  def checkout
    @new_order = current_order
    redirect_to @new_order.paypal_url(accounts_path)
  end

  def hook
    binding.pry
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @order = Order.find params[:invoice]
      @order.order_status.update_attributes notification_params: params, status: status, transaction_id: params[:txn_id], purchased_at: Time.now
    end
    render nothing: true
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def show; end


  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.user_id = current_user.id
    if @student.save
      redirect_to accounts_path, notice: "New Student Created"
    else
      redirect_to :back, notice: "Sorry. There was an error."
    end
  end

  def edit
  end

  def destroy
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
               concat message
      end)
    end
    nil
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/accounts/new.html.erb
<%= simple_form_for @account do |f| %>
  <%= f.input :email, placeholder: 'user@domain.com' %>
  <%= f.button :submit %>
<% end %>

app/views/accounts/show.html.erb
<% unless current_user.account.present? %>
  <br>
  <%= link_to("Click Here to set up your Account", new_accounts_path, class:"h4") %>
<% else %>
  <%= render partial: 'nav/top_fixed'  %>
  <div>
    <h4>Personal Information</h4>
    <h4>Name: <%= "#{current_user.first_name} #{current_user.last_name}" %></h4>
    <h4>Acocunt Number: <%= current_user.id %></h4>
    <hr>
    <h4>Students: </h4>
    <!--  -->
    <table>
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% current_user.students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <!--  -->
    <hr>
    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <div class="form-group">
          <%= simple_form_for @student do |f| %>
            <%= f.input :name, placeholder: 'Add a students name' %>
            <%= f.button :submit %>
          <% end %>
        </div>
      </div>
    </div>
    <button class="btn btn-primary">Id like to be added to the mailing list</button>
  </div>
  <h4>Current Course Information</h4>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th>Last Date Used</th>
          <th>Program</th>
          <th>Current Section</th>
          <th>Progress</th>
          <th>Phase</th>
          <th>For Student</th>
        </tr>
        <tbody>
          <tr>
            <th><%= Time.now.to_s(:short) %></th>
            <th>One</th>
            <th>Laterality Development</th>
            <th>one of three</th>
            <th>Two</th>
            <th>Bobby Tables <button class="btn btn-warning btn-xs">Launch</button></th>
          </tr>
        </tbody>
      </thead>
    </table>
  </div>
  <hr>
  <div>
    <h4>Courses Purchased</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Program Name</th>
          <th>Date Purchased</th>
          <th>Date Completed</th>
          <th>Certificiates</th>
          <th></th>
        </tr>
        <tbody>
          <tr>
            <td>One</td>
            <td><%= Time.now.to_s(:short) %></td>
            <td><%= Time.now.to_s(:short) %></td>
            <td>
              <button class="btn btn-success btn-xs">View</button>
              <button class="btn btn-primary btn-xs">Print</button>
              <button class="btn btn-success btn-xs">Download</button>
            </td>
            <td><button class="btn btn-success btn-xs">Buy Again</button></td>
          </tr>
        </tbody>
      </thead>
    </table>
  </div>
<% end %>

app/views/carts/_cart_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-8">
      <h4><%= program.name %></h4>
    </div>
    <div class="col-xs-4">
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :program_id, value: program.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the program '#{order_item.program.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @order_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<% if @order_items.size == 0 %>
    <p class="text-center">
      There are no items in your shopping cart. Please <%= link_to "go back", root_path %> and add some items to your
      cart.
    </p>
<% else %>
    <% @order_items.each do |order_item| %>
        <%= render 'carts/cart_row', program: order_item.program, order_item: order_item, show_total: true %>
    <% end %>
<% end %>

<%= link_to 'Checkout', checkout_store_path, class: 'btn btn-success', method: :post %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>